apiVersion: apps/v1
kind: Deployment
metadata:
  name: appb
spec:
  selector:
    matchLabels:
      run: appb
  replicas: 1
  template:
    metadata:
      labels:
        run: appb
    spec:
      containers:
      - name: appb
        image: 847137928610.dkr.ecr.us-east-1.amazonaws.com/appb:latest
        ports:
        - containerPort: 5000

